# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder

WORKDIR /app

# Install deps and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and install production deps
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Default command
CMD ["node", "dist/index.js"]
